# Generated by Django 2.2.5 on 2019-10-12 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191012_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 14, 24, 21, 685931, tzinfo=utc)),
        ),
    ]
